### ISSUE TITLE
Prepare AET Developer Guide

### ISSUE THREAD

**Issue by Skejven** [Cognifide/aet#10]
Developer Guide should describe in details how to create new AET module (e.g. collector and comparator).
Maybe a good idea would be to create maven archetype?

**Comment by Skejven** [comment]
TODO:
- [ ] Create guide how to create a collector/modifier
- [ ] Create guide how to create a comparator
- [ ] Create guide how to create a data filter
- [ ] Provide Maven Archetype for a collector/modifier
- [ ] Provide Maven Archetype for comparator
- [ ] Provide Maven Archetype for data filter
- [ ] Write Best Practices
